services:
  myflix:
    mem_limit: 1536m
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=DEBUG
      - MEDIA_PATH=/media
      - MEDIA_INCLUDE_FOLDERS=Filmek,Sorozatok
      - HLS_PATH=/data/hls
      - DB_PATH=/data/myflix
      - HLS_IDLE_TIMEOUT_MINUTES=1
      - HLS_CLEANUP_INTERVAL_MINUTES=1
      - WATCHER_DEBOUNCE_MINUTES=10
      - FILE_INFO_PURGE_INTERVAL_HOURS=24
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TMDB_API=${TMDB_API}
    volumes:
      - media:/media:ro
      - ./test-data:/data

volumes:
  media:
    driver: local
    driver_opts:
      type: cifs
      device: "//${NAS_HOST}/${NAS_SHARE}"
      o: "username=${NAS_USER},password=${NAS_PASSWORD},vers=3.0,ro"